export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body data-new-gr-c-s-check-loaded="14.1246.0" data-gr-ext-installed="">
        <header style={{ padding: "1rem", backgroundColor: "lightblue" }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ padding: "1rem", backgroundColor: "lightgray" }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
